name: End To End Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UI
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: e2e/go.mod
          cache: true
          cache-dependency-path: e2e/go.sum
      - name: Checkout and setup Node
        uses: ./.github/actions/checkout-and-setup
      - name: Build UI
        run: |
          VITE_API="" pnpm build:local
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          repository: temporalio/cli
          path: cli
      - name: Install CLI
        run: |
          cd cli && go install ./cmd/temporal
      - name: Run Playwright Tests
        working-directory: e2e
        run: |
          pnpm install
          npx playwright install chromium --with-deps
          pnpm run test:server &
          pnpm run test:worker &
          pnpm run test:workflows
          pnpm run test
